#!/bin/sh

# This script runs when init it run during the boot process.
# Mounts everything in the fstab

mount -a
mount -o remount +w /

#
# Mount the RAM filesystem to /tmp
#

#mount -t ramfs -n none /tmp
mount -t tmpfs tmpfs /tmp -o size=2048k
export PATH=$PATH:/etc/ath

##
## Put the names of the interfaces in the environmental variables
## (They can be board unique)
##

#export ETH0=eth0
#export ETH1=eth1

#ifconfig $ETH0 up
#ifconfig $ETH1 up
#/etc/rc.d/rc.network
#/etc/rc.d/rc.bridge

#if [ "${WLAN_ON_BOOT}" = "y" ]; then
#    /etc/rc.d/rc.wlan up
#    /etc/ath/apup
#fi

/usr/sbin/telnetd
rc init &
